---
title: "Accidents Analysis Across Italy"
format:
  html:
    theme: default
    toc: true
    number-sections: true
---

*Required Libraries*
```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(accidentr)
library(ggplot2)
library(plotly)
library(dplyr)
library(scales)
library(tidyr)
```

*Load the data*
```{r}
data(Ita_Regions)
```

*overview of the data*
```{r}
str(Ita_Regions)
```


*Check for missing values*
```{r}
sapply(Ita_Regions, function(x) sum(is.na(x)))
```
*Check for unique values in every columns*
```{r}
sapply(Ita_Regions, function(x) length(unique(x)))
```



*Extract the number of accidents everyday*

```{r}
dataACC <- Ita_Regions %>% 
  count(DataAccadimento) %>%
  #summarise(n = sum(n)) %>%
  #mutate(dat = as.Date(DataAccadimento, format = "%m/%d/%Y"))  
  group_by(DataAccadimento)
#dataACC
```

*Exreact the day, month and year*

```{r}
data2 <- dataACC
data2$Date_Time <- strptime(data2$DataAccadimento, format = "%d/%m/%Y")
data2$Day <- format(data2$Date_Time, "%d")
data2$Month <- format(data2$Date_Time, "%m")
data2$NameMonth <- format(data2$Date_Time, "%b")
data2$Year <- format(data2$Date_Time, "%Y")

```

*aggregate number of accidents by year*

```{r}
mydata_total <- data2 %>% 
  group_by(Year) %>%
  summarise(total = sum(n)) 
mydata_total
```

```{r}
ggplot(mydata_total, 
       aes(x = Year, 
           y = total)) +
  geom_line(size = 1.5, 
            color = "lightgrey") +
  geom_point(size = 3, 
             color = "steelblue") +
  labs(y = "Number of Accidents (years)", 
       x = "Year",
       title = "Number of Accidents changes over time",
       subtitle = "Italy (2017-2021)",
       caption = "Source: https://dati.inail.it/opendata/default/Infortuni/index.html")
```


*Aggregate number of accidents by month spread across the years*
```{r}
mydata <- data2 %>% 
  group_by(Year, Month, NameMonth) %>%
  summarise(total = sum(n)) %>%
  spread(key = "Year", value = total) 
mydata
```


# Data Visualization


```{r}
plotdata <- Ita_Regions %>%
  count(Gestione) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))

# plot the bars as percentages, 
# in decending order with bar labels
ggplot(plotdata, 
       aes(x = reorder(Gestione, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "Gestione", 
       y = "Percent", 
       title  = "Participants by Gestione")
```

```{r}
library(treemapify)
# create a treemap with tile labels
plotdata <- Ita_Regions %>%
  count(SettoreAttivitaEconomica)

ggplot(plotdata, 
       aes(fill = SettoreAttivitaEconomica, 
           area = n, 
           label = SettoreAttivitaEconomica)) +
  geom_treemap() + 
  geom_treemap_text(colour = "white", 
                    place = "centre") +
  labs(title = "Accidents by Location") +
  theme(legend.position = "none")
```


```{r}
ggplot(Ita_Regions, 
       aes(x = Eta, 
           y= ..count.. / sum(..count..))) +
  geom_histogram(fill = "cornflowerblue", 
                 color = "white", 
                 binwidth = 5) + 
  labs(title="Participants by age", 
       y = "Percent",
       x = "Age") +
  scale_y_continuous(labels = percent)
```



